### ISSUE TITLE
[Feature Request] Multiple-level sort

### ISSUE THREAD

**Issue by jkottler** [Vinzent03/obsidian-sort-and-permute-lines#19] opened 2022-12-01 19:47 UTC
I would love to see this be able to sort headings *and* their contents.

So that a list like:

- Boots
  - Work
  - Cowboy
- Apples
  - Red Delicious
  - Honeycrisp

Would be transformed into a list like this:
- Apples
  - Honeycrisp
  - Red Delicious
- Boots
  - Cowboy
  - Work

**Comment by Vinzent03** [comment] 2022-12-01 19:52
These are not headings, but simply lists. Headings start with `#`.
This is achievable with the newest update. Use the command `Sort current list recursively`
Duplicate of #16

**Closed by Vinzent03** 2022-12-01 19:52 UTC
